### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by PunGrumpy** [Mephisto-Grumpy/github-crash-course#1]
I think it look better if the main title is a bit more orange.

The styling rule colud be like this:

```css
h1 {
  color: #efa82e;
}
```
